### ISSUE TITLE
Constructor of RestExecutionService fails

### ISSUE THREAD

**Issue by askask** [eilslabs/BatchEuphoria#85]
with this exception:

```
java.lang.NullPointerException
	at java.time.Duration.between(Duration.java:473)
	at de.dkfz.roddy.execution.RestExecutionService.execute(RestExecutionService.groovy:171)
	at de.dkfz.roddy.execution.RestExecutionService.logon(RestExecutionService.groovy:111)
	at de.dkfz.roddy.execution.RestExecutionService.<init>(RestExecutionService.groovy:92)
	at de.dkfz.tbi.otp.job.processing.ClusterJobManagerFactoryService.getJobManager(ClusterJobManagerFactoryService.groovy:36)
…
```

**Comment by vinjana** [comment]
LSFRest is currently not used. The issue will be closed (probably fixed).
